### ISSUE TITLE
Salt mount.mounted fails

### ISSUE THREAD

**Issue by votdev** [OpenMediaVault-Plugin-Developers/openmediavault-unionfilesystems#32]
It seems Salt does not support fuse.mergerfs mount points really well.

```
# >>> [openmediavault]
/dev/disk/by-label/8tbbackupcopy		/srv/dev-disk-by-label-8tbbackupcopy	ext4	defaults,nofail,user_xattr,noexec,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl	0 2
/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi0-0-2-part1		/srv/dev-disk-by-id-scsi-0QEMU_QEMU_HARDDISK_drive-scsi0-0-2-part1	ext4	defaults,nofail,user_xattr,noexec,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl	0 2
/srv/dev-disk-by-label-8tbbackupcopy:/srv/dev-disk-by-id-scsi-0QEMU_QEMU_HARDDISK_drive-scsi0-0-2-part1		/srv/e466dfcd-337e-4c4f-89c2-17bebc3098b3	fuse.mergerfs	defaults,allow_other,direct_io,use_ino,category.create=epmfs,minfreespace=4G	0 0
# <<< [openmediavault]
```

```
----------
          ID: mount_no_bind_mountpoint_6176653e-1c11-4404-b4bf-a611a51880c5
    Function: mount.mounted
        Name: /srv/e466dfcd-337e-4c4f-89c2-17bebc3098b3
      Result: False
     Comment: fuse: missing mountpoint parameter
     Started: 07:54:51.179638
    Duration: 110.404 ms
     Changes:   
              ----------
              umount:
                  Forced unmount because devices don't match. Wanted: e466dfcd-337e-4c4f-89c2-17bebc3098b3, current: label-8tbbackupcopy:id-scsi-0QEMU_QEMU_HARDDISK_drive-scsi0-0-2-part1, /home/vagrant/openmediavault/openmediavault/label-8tbbackupcopy:id-scsi-0QEMU_QEMU_HARDDISK_drive-scsi0-0-2-part1
```

Because of that i think about relocating the mount process into every *.sls file, so custom settings can be applied easily. E.g. i get rid of the unmount error using 

```
{% for mountpoint in no_bind_mountpoints %}
mount_no_bind_mountpoint_{{ mountpoint.uuid }}:
  mount.mounted:
    - name: {{ mountpoint.dir }}
    - device: {{ mountpoint.fsname | replace('\\', '\\\\') }}
    - fstype: {{ mountpoint.type }}
    - mkmnt: True
    - persist: False
    - mount: True
    - device_name_regex:
      - ({{ mountpoint.fsname | replace('\\', '\\\\') | replace(':', '|') }})
{% endfor %}
```

But it requires still more work

```
          ID: mount_no_bind_mountpoint_6176653e-1c11-4404-b4bf-a611a51880c5
    Function: mount.mounted
        Name: /srv/e466dfcd-337e-4c4f-89c2-17bebc3098b3
      Result: False
     Comment: fuse: missing mountpoint parameter
     Started: 08:03:18.023330
    Duration: 52.247 ms
     Changes:   
```

Because of that i think it's a good idea to force each plugin to take care about the mounting of its fstab entries.

I will share the PR as soon as it's ready.

**Comment by votdev** [comment]
Maybe it's a good idea to use the [mount module](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.mount.html) instead of the [state](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.mount.html) for mergerfs and use a test if it's necessary to mount the filesystem.

**Comment by votdev** [comment]
Good starting point would be:

```
create_unionfilesystem_mountpoint_{{ pool.self_mntentref }}:
  file.accumulated:
    - filename: "/etc/fstab"
    - text: "{{ branchDirs | join(':') }}\t\t{{ mntDir }}\tfuse.mergerfs\t{{ options | join(',') }}\t0 0"
    - require_in:
      - file: append_fstab_entries

mount_unionfilesystem_mountpoint_{{ pool.self_mntentref }}:
  mount.mounted:
    - name: {{ mntDir }}
    - device: {{ branchDirs | join(':') }}
    - fstype: fuse.mergerfs
    - mkmnt: True
    - persist: False
    - mount: True
    - device_name_regex:
      - ({{ branchDirs | join('|') }})
```

Please take care that the ID's are unique: ``create_filesystem_mountpoint_xxx`` already exists, so name it like ``create_unionfilesystem_mountpoint_xxx``.

**Comment by votdev** [comment]
I think the best solution is
```
create_unionfilesystem_mountpoint_{{ pool.self_mntentref }}:
  file.accumulated:
    - filename: "/etc/fstab"
    - text: "{{ branchDirs | join(':') }}\t\t{{ mntDir }}\tfuse.mergerfs\t{{ options | join(',') }}\t0 0"
    - require_in:
      - file: append_fstab_entries

is_unionfilesystem_mountpoint_{{ pool.self_mntentref }}_mounted:
  module.run:
    - mount.is_mounted:
      - name: {{ mntDir }}

mount_unionfilesystem_mountpoint_{{ pool.self_mntentref }}:
  cmd.run:
    - name: "mount {{ mntDir }}"
    - onfail:
      - is_unionfilesystem_mountpoint_{{ pool.self_mntentref }}_mounted
{% endfor %}
```

**Comment by ryecoaaron** [comment]
The mount point still fails to be created before the pool is mounted.  The directory is there but somehow the pool is mounted before it is created?

**Comment by ryecoaaron** [comment]
This should be fixed now.

**Comment by mike391** [comment]
This is still broken on OMV5. Creating a new pool shows the error:
`: Missing 'required' attribute 'self_mntentref'.`
