### ISSUE TITLE
Can't add share folders after creating union fs

### ISSUE THREAD

**Issue by SlowLogicBoy** [OpenMediaVault-Plugin-Developers/openmediavault-unionfilesystems#35]
Reproduce:
1. Installed OMV5 (on usb flash drive)
2. apt update && apt upgrade
3. Installed OMV5 Extras
4. Installed flashmemory plugin and configured it (just in case this is relevant)
5. Reboot
6. Install unionfilesystems plugin
7. Add union file system:
![image](https://user-images.githubusercontent.com/3121637/73590749-beaaef00-44ee-11ea-8d0d-15d3769fa901.png)
![image](https://user-images.githubusercontent.com/3121637/73590751-c8cced80-44ee-11ea-846a-0f0967fce56f.png)
8. go to Shared folders, click add and in the popup or when trying to expand device combobox/dropdown I get:
```
Error #0:
OMV\Rpc\Exception: Invalid RPC response. Please check the syslog for more information. in /usr/share/php/openmediavault/rpc/rpc.inc:187
Stack trace:
#0 /usr/share/php/openmediavault/rpc/proxy/json.inc(97): OMV\Rpc\Rpc::call('ShareMgmt', 'getCandidates', Array, Array, 3)
#1 /var/www/openmediavault/rpc.php(45): OMV\Rpc\Proxy\Json->handle()
#2 {main}
```
Syslog:
![image](https://user-images.githubusercontent.com/3121637/73590859-3fb6b600-44f0-11ea-9ca3-44820a49b164.png)

**Notes:**
Before adding union file system I can add shared folders, and if I remove union file system I can again add shared folder.

here is [config.xml](https://gist.github.com/SlowLogicBoy/1e8c60aae2dfd3bfc214f49067ed6043) in case.

**Comment by brumela** [comment]
I can confirm that bug. My setup Omv 5.2.6-1, openmediavault-unionfilesystems 5.1.

**Comment by ryecoaaron** [comment]
Follow this issue - https://github.com/openmediavault/openmediavault/issues/583

**Comment by SuperLuckyCharms** [comment]
Getting the exact same issue as everyone else.  Brand new install using OMV5 script.

**Comment by ryecoaaron** [comment]
Everyone is since it is caused by an OMV change.  The fix is here - https://github.com/openmediavault/openmediavault/pull/587 - but you will have to manually change the files or wait for the release.  Nothing else I can do.

**Comment by ryecoaaron** [comment]
This should be fixed after you install the OMV 5.2.7 update that is available now.

**Comment by SuperLuckyCharms** [comment]
That's awesome news Aaron. But it still shows version 5.1 in the gui even
after I did an omv-update.

Thanks and I appreciate the help.

-Loc

**Comment by SuperLuckyCharms** [comment]
Never mind. I just figured it out. Thanks again!
